### ISSUE TITLE
Relation mode not in the tool bar

### ISSUE THREAD

**Issue by Ninonija** [pelagios/pelagios.github.io#10]
Hey there, 

I can not see the relation mode for annotations in the tool bar. How can change it?
Thanks!

**Comment by rsimon** [comment]
Do you mean the toolbar in Recogito, as shown in the screenshot here?

https://recogito.pelagios.org/help/relations

Can you send us a screenshot of what you are seeing? Plus information on the browser you are using? (MS Edge and IE are not supported. Although this should not have an effect on the visibility of the menu option.)

**Comment by rsimon** [comment]
P.S.: are you in text or image annotation mode? Relationship annotation is only available for texts.

**Comment by Ninonija** [comment]
ah - that is the issue - I am in the image annotation mode - but I would need as well the relationship annotation for images

**Comment by rsimon** [comment]
We'd love to build that, too. But don't currently have any resources to do that. (We're looking for projects to support further development, wink wink ;-)

In fact there is a chance that we will be able to start working on this next year. But we won't know until December whether that will happen.

**Comment by Ninonija** [comment]
ok, good to know
and Thank you!
