### ISSUE TITLE
partner-url in "partners" fails

### ISSUE THREAD

**Issue by florianthiery** [pelagios/pelagios.github.io#22]
if a HTTP in a "partner-url" on the partner site appears, this leads to http//xyz without a :

**Comment by florianthiery** [comment]
partner-url sais <a href="http://{{ partner.partner-url }}"> if the partner-url starts with http:// this will be written twice

**Comment by florianthiery** [comment]
solution: delete http:// in partners.html and fix urls in partner mds

**Comment by florianthiery** [comment]
partler-urls fixed, may have a look @RebeccaKahn et al.?

**Comment by RebeccaKahn** [comment]
Thanks! Another thing to add to the documentation.
